export const GET_DEMAND_LIST_ACTION = 'GET_DEMAND_LIST_ACTION'
export const DELETE_DEMAND_LIST_ACTION = 'DELETE_DEMAND_LIST_ACTION'
export const GET_CURRENT_DEVICE = "GET_CURRENT_DEVICE"
export const CLEAR_CURRENT_DEVICE = "CLEAR_CURRENT_DEVICE"
export const GET_GATEWAY_ID = "GET_GATEWAY_ID"
export const GET_METER_LIST = "GET_METER_LIST"

// 重置
export const RESET_STORE_DATA = "RESET_STORE_DATA"

// 設定
export const CHANGE_DEMAND_VALUE = "CHANGE_DEMAND_VALUE"
export const CHANGE_DEMAND_ALARM = "CHANGE_DEMAND_ALARM"
export const CHANGE_DEMAND_MODE = "CHANGE_DEMAND_MODE"
export const CHANGE_DEMAND_OFFSET = "CHANGE_DEMAND_OFFSET"

export const CHANGE_OFFLOADLIST = "CHANGE_OFFLOADLIST"
export const ADD_ALARMLIST = "ADD_ALARMLIST"
export const DELETE_ALARMLIST = "DELETE_ALARMLIST"
export const ADD_OFFLOADLIST = "ADD_OFFLOADLIST"
export const DELETE_OFFLOADLIST = "DELETE_OFFLOADLIST"


// 儲存
export const MODIFY_DEMAND_LIST = "SAVE_DEMAND_LIST"
export const ADD_DEMAND_LIST = "ADD_DEMAND_LIST"

// 套用
export const COMMIT_TO_LIST = "COMMIT_TO_LIST"
